version: '3.8'

services:
  backend:
    build: ./backend
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - SPRING_APPLICATION_NAME=auto
      # -----------------------------------------------------------
      # KRİTİK DÜZELTME 1: ADRES
      # Docker içinde 'localhost' yazarsan backend KENDİ İÇİNE bakar.
      # Veritabanına gitmek için servis adı olan 'db' yazmalısın.
      # -----------------------------------------------------------
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=9927
      
      # Hibernate Ayarları
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=public
    depends_on:
      db:
        condition: service_healthy # DB hazır olmadan başlama
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9927
    volumes:
      - pg_data:/var/lib/postgresql/data
      # -----------------------------------------------------------
      # KRİTİK DÜZELTME 2: ŞEMA OLUŞTURMA
      # Senin oluşturduğun init.sql dosyasını içeri atıyoruz.
      # Bu sayede DB ilk açıldığında 'test' şemasını otomatik kuracak.
      # -----------------------------------------------------------
      - ./init.sql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: